package spring.learn.domain;

import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;

// represents a JPA (Jakarta EE Persistence API; same thing) entity
@Entity
public class Employee {

    @Id
    @GeneratedValue
    private UUID id; // the @Id annotation indicates that this class field is the primary key
    private String name;
    private String role;

    // zero-parameter constructor
    public Employee() {}

    // constructor with name and role; id is presumably autogenerated
    public Employee(String name, String role) {
        this.name = name;
        this.role = role;
    }

    public UUID getId() {
        return id;
    }
    public String getName() {
        return name;
    }
    public String getRole() {
        return role;
    }

    public void setId(UUID id) {
        this.id = id;
    }
    public void setName(String name) {
        this.name = name;
    }
    public void setRole(String role) {
        this.role = role;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Employee)) return false;
        Employee employee = (Employee) o;
        return Objects.equals(id, employee.id) && Objects.equals(name, employee.name) && Objects.equals(role, employee.role);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id, this.name, this.role);
    }

    @Override
    public String toString() {
        return "Employee{" + "id=" + this.id + ", name='" + this.name + '\'' + ", role='" + this.role + '\'' + '}';
    }
}
